[build]
  command = "npm ci --legacy-peer-deps && npm run build"
  publish = "web-dist"
  edge_functions = "functions"

[build.environment]
  SUPABASE_URL = ""
  SUPABASE_KEY = ""

[[edge_functions]]
  path = "/api/chat"
  function = "chat"
