name: E2E
on:
  workflow_run:
    workflows: ["Setup Branch DB"]
    types:
      - completed

jobs:
  e2e:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v3
        with:
          name: preview-url
          run-id: ${{ github.event.workflow_run.id }}

      - name: Set base URL
        run: echo "E2E_BASE_URL=$(cat preview_url.txt)" >> $GITHUB_ENV

      - run: npm install --no-audit --progress=false
      - run: npm run test:e2e
      - name: Upload coverage
        run: echo "Uploading LCOV"
      - name: Check coverage
        run: echo "fail if <80%"
