name: Setup Branch DB
on:
  push:
    branches: ["*"]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init Supabase
        run: echo "Initializing supabase"
      - name: Create branch DB
        run: echo "supabase db branch ${{ github.ref_name }}"
      - name: Apply migrations
        run: echo "supabase db push"
      - name: Seed data
        run: echo "supabase db execute packages/testing/seed.sql"
      - name: Export env
        run: echo "supabase functions env pull"
      - name: Trigger Netlify preview
        run: echo "netlify build"
