# .github/workflows/test.yml
name: Test

on:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install all dependencies (no lock-file, tolerate peer-deps)
      - name: Install dependencies
        run: npm install --no-audit --legacy-peer-deps --progress=false

      # Lint (optional – comment out if you don’t have ESLint setup yet)
      - name: Lint
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script; skipping."
          fi

      # Type-check (optional – comment out if tsconfig not ready yet)
      - name: Type check
        run: |
          if npm run | grep -q "typecheck"; then
            npm run typecheck
          else
            echo "No typecheck script; skipping."
          fi

      # Run the single passing unit test (Vitest)
      - name: Unit tests
        run: npm run test:unit
