# .github/workflows/test.yml   ❶  paste this entire file
name: Unit-CI-placeholder
on:
  pull_request:

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies (no lock-file)
        run: npm install --no-audit --legacy-peer-deps --progress=false

      - name: CI placeholder
        run: echo "✅ basic CI passed"
